### PR TITLE
Test on Python 3.12

### PR DESCRIPTION
**Pull request by cclauss**
https://www.python.org/downloads/release/python-3120/

### CODE REVIEW

**Comment by mtreinish** [comment]
I think the failures in tests here are because testtools isn't compatible with Python 3.12. This PR: https://github.com/testing-cabal/testtools/pull/353 fixes it on main, but it hasn't been released yet.

**Comment by jcapiitao** [comment]
The patch can be rebased as testtools is now availalble for Python3.12 since 2.7.0 [1]

[1] https://pypi.org/project/testtools/2.7.0/

**Review by mtreinish — APPROVED** [review]

**Comment by jcapiitao** [comment]
Thank you guys, do you plan to issue a new release supporting py3.12 soon ? No pressure, just wondering

**Comment by mtreinish** [comment]
We can push out a quick bugfix release if needed, but there weren't any code changes associated with this PR. So the bugfix would just be package metadata. This PR was just adding the 3.12 testing to CI, I believe the 4.1.0 release should be 3.12 compatible. We were blocked on testing in CI before because our upstream dependencies weren't 3.12 compatible in a release yet. But now that's been solved installing 4.1.0 should work. If it doesn't definitely open an issue and we can quickly push out 4.1.1

**Comment by jcapiitao** [comment]
Great, thank you @mtreinish  :+1:

**Pull request merged**
