### PR TITLE
Add appveyor ci config

### PR DESCRIPTION
**Pull request by mtreinish**
This commit adds an appveyor config file to run stestr in windows.

### CODE REVIEW

**Comment by mtreinish** [comment]
This still doesn't work, but the tests are actually running now. There are 7 failures when running on windows. I think most (if not all) are related to filesystem access

**Comment by mtreinish** [comment]
@masayukig since I know you like windows so much :p do you want to have a go at fixing the unit test failures here?

**Comment by masayukig** [comment]
heh, I'll try! I don't like windows that much, though :-p

**Comment by mtreinish** [comment]
I'm pretty sure this is finally working. But, I'll wait for the windows CI (it's kinda slow and runs jobs serially) to finish to confirm before merging.

**Comment by masayukig** [comment]
Thank you and I'm sorry for not doing this. Yeah, looks good to me.

**Pull request merged**
