### PR TITLE
Add support for python 3.7

### PR DESCRIPTION
**Pull request by mtreinish**
Python 3.7 is out and some distros are already using it (including mine,
archlinux) so we should add official support for it. It doesn't appear
that there are any functional changes needed. This commit just updates
the package metadata and adds python 3.7 test jobs.

### CODE REVIEW

**Comment by mtreinish** [comment]
hmm, I guess we'll need to figure out how to change the distro it's running on for travis. Because the trusty image it's defaulting to won't work with >=3.7 because of a openssl lib. (which is why the binary to download/run isn't found during the job)

**Comment by mtreinish** [comment]
@masayukig do you have any idea what I'm doing wrong in the travis config? According to every reference I've found by searching says that you just specify `dist: xenial` and `python: 3.7` and it should work.

**Comment by mtreinish** [comment]
This is the last patch in the queue after we figure this out and merge it I'm planning to push 2.1.1 so we can get the unxsuccess patch out there for people.

**Comment by masayukig** [comment]
I'm not sure but this could help?

https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
```
language: python
python: 3.7
dist: xenial
sudo: true
```
add `sudo: true` ?

**Comment by mtreinish** [comment]
@masayukig hah, well it looks like `sudo: true` was the missing piece after all.

**Comment by masayukig** [comment]
awesome :)

**Pull request merged**
