### PR TITLE
Add README_ja.rst

### PR DESCRIPTION
**Pull request by masayukig**
This commit adds README_ja.rst which is a Japanese translation of
README.rst. This might be helpful to encourage to use stestr and to
participate development for Japanese.

### CODE REVIEW

**Comment by masayukig** [comment]
> LGTM, I'll defer to you on the actual translation. But, the only thing I think we should make sure to do here is link to the translated version off the main `README.rst` fail I would just add a line like:
> 
> ```
> * Read this in other languages: `English`_, `日本語`_
> 
> .. _English: https://github.com/mtreinish/stestr/blob/master/README.rst
> .. _日本語: https://github.com/mtreinish/stestr/blob/master/README_ja.rst
> ```
> 
> right below the links at the start of the README. That way it'll be clear where to find to the translated version.

Thanks. Yeah, that looks better. I'll push a patch :)

**Comment by mtreinish** [comment]
We probably should also add the equivalent line to the ja version too (so it links back to English)

**Comment by masayukig** [comment]
yeah, that makes sense.

**Comment by masayukig** [comment]
So, should we have the English version link in README.rst? I think that should be the same as a user looking at.

.. _English: https://github.com/mtreinish/stestr/blob/master/README.rst

**Comment by masayukig** [comment]
Yeah, I agree with that the ja README in the en docs is a bit confusing. But as a starting point to have translated copies, I think just adding a translated README is not so bad. To be more generic/sophisticated, I need to know more readthedocs.io, zanata, sphinx, pot/po files etc. It shouldn't be so hard but I'm very new to like those things yet. 

As a next step, I made the locale and put the translated file[0]. We can generate Japanese documents like this.
```
sphinx-build -c doc/source -b html -D language=ja  doc/source doc/build
```

[0] https://github.com/masayukig/stestr/tree/i18n/doc/source/locale/ja/LC_MESSAGES

**Pull request merged**
