### PR TITLE
Add readme note about python 2 eol in readme

### PR DESCRIPTION
**Pull request by mtreinish**
Now that we're getting ready to drop python 2 support for an stestr
3.0.0 release in early 2020 this commit adds a release note to make the
plans clear to end users.

### CODE REVIEW

**Comment by mtreinish** [comment]
@masayukig I was also debating adding a deprecation warning if python2 was used. But I'm wondering if that's too noisy for users. Do you have any thoughts?

**Comment by masayukig** [comment]
Yeah, I think adding a deprecation warning is good. It might be a bit too noisy but it's necessary to advertise.

**Comment by masayukig** [comment]
This works in my environment at least.
```
$ PYTHONWARNINGS=all stestr run
/home/masayuki/git/stestr/.tox/py27/bin/stestr:10: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Support for using python 2.7 with stestr will be removed in the 3.0.0 release in early 2020
 :
```

**Comment by mtreinish** [comment]
@masayukig Is there anything else left to do on this?

**Comment by masayukig** [comment]
Nope. I think we can merge this now.

**Pull request merged**
