### PR TITLE
Add support to repositories for storing run metadata

### PR DESCRIPTION
**Pull request by mtreinish**
This commit adds repository APIs around storing and accessing run
metadata strings. The concept being that you can store a metadata string
to identify a run by some other identifier then the run id. The example
use case in mind for this feature is using it to store a VCS commit hash
(like a git sha1) or identifier. The APIs in this commit allow storing
metadata at run creation time, accessing the metadata for a run, and
finding run_ids by a metadata value. This is implemented for both the
file and sql repository types. The memory repository type does not have
this implemented, as it is more limited.

Related to: #224

### CODE REVIEW

**Comment by mtreinish** [comment]
This is still a work in progress because I need to add test cases. Once this feature is tested it should be good to go.

**Comment by aspiers** [comment]
Coooool :-)

**Comment by mtreinish** [comment]
@masayukig I just added skips for those 2 failing tests on windows. I don't know why tempfile fails there but not in other places on appveyor. But it seems like just an env issue and nothing to do with the code.

**Comment by masayukig** [comment]
yeah, I don't know why either. If we can find the cause of failures, we'll be able to reenable them in the future.

**Pull request merged**
